[tool.poetry]
name = "prisma-orm-example"
version = "0.1.0"
description = ""
authors = ["Thomas Perelle <thomas@perelle.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
prisma = "^0.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
